name: Greeting and Count Repository Files

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  greeting:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Greeting
        env:
         STUDENT_NAME: ${{ vars.STUDENT_NAME }}
        run: |
          echo "👋 Hello, ${{env.STUDENT_NAME}}"

      - name: Count Repository Files
        run: |
          FILE_COUNT=$(find . -type f -not -path '*/.*' | wc -l)
          echo "📁 Total files (Excluded sicret files)in this repository is : $FILE_COUNT"